-- Auto-generated by omw dungeon generate — do not edit
local JTT_Dungeons = {
  spider_cave = {
    variants = {
      {
        cell_id = "jtt_spider_cave_0",
        entrance_pos = {x=2816.0, y=1024.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2816.0, y=1024.0, z=0.0}, {x=3840.0, y=8960.0, z=0.0}, {x=3840.0, y=3072.0, z=0.0}, {x=3840.0, y=12544.0, z=0.0}, {x=9472.0, y=17152.0, z=0.0}, {x=17152.0, y=5120.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_1",
        entrance_pos = {x=1280.0, y=13568.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1280.0, y=13568.0, z=0.0}, {x=4352.0, y=16896.0, z=0.0}, {x=13312.0, y=7680.0, z=0.0}, {x=15616.0, y=9216.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_2",
        entrance_pos = {x=7680.0, y=1792.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=7680.0, y=1792.0, z=0.0}, {x=12288.0, y=5888.0, z=0.0}, {x=13568.0, y=13056.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_3",
        entrance_pos = {x=5632.0, y=17664.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=5632.0, y=17664.0, z=0.0}, {x=8960.0, y=8448.0, z=0.0}, {x=16128.0, y=2816.0, z=0.0}, {x=16128.0, y=13824.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_4",
        entrance_pos = {x=2816.0, y=1024.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2816.0, y=1024.0, z=0.0}, {x=2816.0, y=7936.0, z=0.0}, {x=6400.0, y=4096.0, z=0.0}, {x=13568.0, y=16128.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_5",
        entrance_pos = {x=4096.0, y=12800.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=4096.0, y=12800.0, z=0.0}, {x=7680.0, y=13824.0, z=0.0}, {x=13312.0, y=4096.0, z=0.0}, {x=13312.0, y=5888.0, z=0.0}, {x=15872.0, y=8448.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_6",
        entrance_pos = {x=2048.0, y=768.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2048.0, y=768.0, z=0.0}, {x=12800.0, y=11264.0, z=0.0}, {x=16384.0, y=7168.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_7",
        entrance_pos = {x=2304.0, y=3328.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2304.0, y=3328.0, z=0.0}, {x=2304.0, y=17152.0, z=0.0}, {x=3584.0, y=14592.0, z=0.0}, {x=4864.0, y=7680.0, z=0.0}, {x=8704.0, y=3328.0, z=0.0}},
      },
    },
    creatures = {"jtt_spider"},
    creatures_per_room = {2, 3},
    containers = {"jtt_loot_small", "jtt_loot_medium"},
    loot_per_room = {0, 1},
  },
}
return JTT_Dungeons