-- Auto-generated by omw dungeon generate — do not edit
local JTT_Dungeons = {
  spider_cave = {
    variants = {
      {
        cell_id = "jtt_spider_cave_7",
        entrance_pos = {x=2304.0, y=3328.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2304.0, y=3328.0, z=0.0}, {x=2304.0, y=17152.0, z=0.0}, {x=3584.0, y=14592.0, z=0.0}, {x=4864.0, y=7680.0, z=0.0}, {x=8704.0, y=3328.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_8",
        entrance_pos = {x=1536.0, y=15872.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1536.0, y=15872.0, z=0.0}, {x=3584.0, y=16896.0, z=0.0}, {x=4864.0, y=7168.0, z=0.0}, {x=13568.0, y=17152.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_9",
        entrance_pos = {x=1792.0, y=13056.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1792.0, y=13056.0, z=0.0}, {x=2304.0, y=4352.0, z=0.0}, {x=5120.0, y=6656.0, z=0.0}, {x=13312.0, y=3840.0, z=0.0}, {x=14592.0, y=6144.0, z=0.0}, {x=16896.0, y=15872.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_10",
        entrance_pos = {x=1280.0, y=7680.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1280.0, y=7680.0, z=0.0}, {x=9984.0, y=6144.0, z=0.0}, {x=11008.0, y=3328.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_11",
        entrance_pos = {x=1536.0, y=6656.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1536.0, y=6656.0, z=0.0}, {x=3584.0, y=2048.0, z=0.0}, {x=4096.0, y=15360.0, z=0.0}, {x=6144.0, y=1280.0, z=0.0}, {x=7168.0, y=6912.0, z=0.0}, {x=15872.0, y=11008.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_12",
        entrance_pos = {x=1024.0, y=5376.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1024.0, y=5376.0, z=0.0}, {x=3328.0, y=14592.0, z=0.0}, {x=3584.0, y=1536.0, z=0.0}, {x=5376.0, y=13056.0, z=0.0}, {x=7168.0, y=2816.0, z=0.0}, {x=16128.0, y=9728.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_13",
        entrance_pos = {x=1536.0, y=14848.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1536.0, y=14848.0, z=0.0}, {x=4864.0, y=3072.0, z=0.0}, {x=8192.0, y=5376.0, z=0.0}, {x=12288.0, y=8192.0, z=0.0}, {x=15104.0, y=14848.0, z=0.0}},
      },
      {
        cell_id = "jtt_spider_cave_14",
        entrance_pos = {x=4864.0, y=9472.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=4864.0, y=9472.0, z=0.0}, {x=8960.0, y=10240.0, z=0.0}, {x=10240.0, y=16128.0, z=0.0}},
      },
    },
    creatures = {"jtt_spider"},
    creatures_per_room = {2, 3},
    containers = {"jtt_loot_small", "jtt_loot_medium"},
    loot_per_room = {0, 1},
  },
}
return JTT_Dungeons