-- Auto-generated by omw dungeon generate — do not edit
local JTT_Dungeons = {
  bear_den = {
    variants = {
      {
        cell_id = "jtt_bear_den_7",
        entrance_pos = {x=1024.0, y=1280.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1024.0, y=1280.0, z=0.0}, {x=3584.0, y=5376.0, z=0.0}, {x=5888.0, y=1024.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_8",
        entrance_pos = {x=1792.0, y=2304.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1792.0, y=2304.0, z=0.0}, {x=5888.0, y=768.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_9",
        entrance_pos = {x=1792.0, y=2048.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1792.0, y=2048.0, z=0.0}, {x=2048.0, y=6400.0, z=0.0}, {x=4864.0, y=4352.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_10",
        entrance_pos = {x=2560.0, y=6656.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2560.0, y=6656.0, z=0.0}, {x=4096.0, y=1792.0, z=0.0}, {x=4352.0, y=7424.0, z=0.0}, {x=4608.0, y=5376.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_11",
        entrance_pos = {x=1536.0, y=4352.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1536.0, y=4352.0, z=0.0}, {x=4864.0, y=5376.0, z=0.0}, {x=7168.0, y=4864.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_12",
        entrance_pos = {x=1792.0, y=3840.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1792.0, y=3840.0, z=0.0}, {x=4608.0, y=2816.0, z=0.0}, {x=5120.0, y=768.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_13",
        entrance_pos = {x=1280.0, y=5120.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1280.0, y=5120.0, z=0.0}, {x=5888.0, y=2560.0, z=0.0}, {x=5888.0, y=6656.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_14",
        entrance_pos = {x=2816.0, y=2560.0, z=50.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2816.0, y=2560.0, z=0.0}, {x=6656.0, y=2816.0, z=0.0}},
      },
    },
    creatures = {"jtt_bear", "jtt_wolf"},
    creatures_per_room = {1, 2},
    containers = {"jtt_loot_small", "jtt_loot_medium"},
    loot_per_room = {0, 1},
  },
}
return JTT_Dungeons