-- Auto-generated by omw dungeon generate — do not edit
local JTT_Dungeons = {
  bear_den = {
    variants = {
      {
        cell_id = "jtt_bear_den_0",
        entrance_pos = {x=24.0, y=108.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=24.0, y=108.0, z=0.0}, {x=44.0, y=72.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_1",
        entrance_pos = {x=44.0, y=20.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=44.0, y=20.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_2",
        entrance_pos = {x=52.0, y=28.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=52.0, y=28.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_3",
        entrance_pos = {x=28.0, y=56.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=28.0, y=56.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_4",
        entrance_pos = {x=104.0, y=56.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=104.0, y=56.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_5",
        entrance_pos = {x=52.0, y=68.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=52.0, y=68.0, z=0.0}, {x=56.0, y=100.0, z=0.0}, {x=76.0, y=12.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_6",
        entrance_pos = {x=24.0, y=92.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=24.0, y=92.0, z=0.0}, {x=44.0, y=68.0, z=0.0}, {x=104.0, y=44.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_7",
        entrance_pos = {x=20.0, y=56.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=20.0, y=56.0, z=0.0}, {x=88.0, y=16.0, z=0.0}},
      },
    },
    creatures = {"jtt_bear", "jtt_wolf"},
    creatures_per_room = {1, 2},
    containers = {"jtt_loot_small", "jtt_loot_medium"},
    loot_per_room = {0, 1},
  },
}
return JTT_Dungeons