-- Auto-generated by omw dungeon generate — do not edit
local JTT_Dungeons = {
  bear_den = {
    variants = {
      {
        cell_id = "jtt_bear_den_0",
        entrance_pos = {x=2816.0, y=4864.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2816.0, y=4864.0, z=0.0}, {x=3072.0, y=1792.0, z=0.0}, {x=7168.0, y=7424.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_1",
        entrance_pos = {x=1536.0, y=4608.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1536.0, y=4608.0, z=0.0}, {x=5888.0, y=3840.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_2",
        entrance_pos = {x=2816.0, y=5632.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=2816.0, y=5632.0, z=0.0}, {x=3584.0, y=7424.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_3",
        entrance_pos = {x=5632.0, y=4608.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=5632.0, y=4608.0, z=0.0}, {x=7424.0, y=4608.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_4",
        entrance_pos = {x=1280.0, y=1280.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1280.0, y=1280.0, z=0.0}, {x=6656.0, y=3840.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_5",
        entrance_pos = {x=1536.0, y=3584.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1536.0, y=3584.0, z=0.0}, {x=3840.0, y=5120.0, z=0.0}, {x=6912.0, y=2560.0, z=0.0}, {x=7168.0, y=6400.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_6",
        entrance_pos = {x=1792.0, y=6144.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1792.0, y=6144.0, z=0.0}, {x=3328.0, y=6912.0, z=0.0}, {x=4608.0, y=7168.0, z=0.0}, {x=6912.0, y=2816.0, z=0.0}},
      },
      {
        cell_id = "jtt_bear_den_7",
        entrance_pos = {x=1024.0, y=1280.0, z=0.0},
        exit_exterior = {cell="", x=4096, y=4096, z=210},
        anchors = {{x=1024.0, y=1280.0, z=0.0}, {x=3584.0, y=5376.0, z=0.0}, {x=5888.0, y=1024.0, z=0.0}},
      },
    },
    creatures = {"jtt_bear", "jtt_wolf"},
    creatures_per_room = {1, 2},
    containers = {"jtt_loot_small", "jtt_loot_medium"},
    loot_per_room = {0, 1},
  },
}
return JTT_Dungeons