# omwtools/omwtools/dungeons/lua_config.py
from .dungeon_spec import DungeonSpec, DungeonLayout


def generate_lua_config(
    type_name: str,
    spec: DungeonSpec,
    layouts: list[DungeonLayout],
    tileset: "TileSet",
    start_seed: int = 0,
) -> str:
    """
    Generate a Lua module string defining the dungeon config table.
    Anchor positions are exported as world coords (tile_grid * tileset.tile_size).
    Returns a string suitable for require() from global.lua.
    """
    ts = tileset.tile_size
    cfg_var = f"{spec.game_prefix.upper()}_Dungeons"
    lines = [f"-- Auto-generated by omw dungeon generate — do not edit"]
    lines.append(f"local {cfg_var} = {{")
    lines.append(f"  {type_name} = {{")
    lines.append("    variants = {")

    for i, layout in enumerate(layouts):
        seed = start_seed + i
        cell_id = f"{spec.game_prefix}_{spec.name}_{seed}"
        etx, ety = layout.entrance_tile
        ex, ey, ez = etx * ts, ety * ts, 0.0
        rx = spec.exterior_return_pos["x"]
        ry = spec.exterior_return_pos["y"]
        rz = spec.exterior_return_pos["z"]
        rc = spec.exterior_return_pos.get("cell", "")
        anchor_strs = ", ".join(
            f"{{x={atx * ts:.1f}, y={aty * ts:.1f}, z=0.0}}"
            for atx, aty in layout.anchor_tiles
        )
        lines.append(f"      {{")
        lines.append(f'        cell_id = "{cell_id}",')
        lines.append(f"        entrance_pos = {{x={ex:.1f}, y={ey:.1f}, z={ez:.1f}}},")
        lines.append(f'        exit_exterior = {{cell="{rc}", x={rx}, y={ry}, z={rz}}},')
        lines.append(f"        anchors = {{{anchor_strs}}},")
        lines.append(f"      }},")

    lines.append("    },")
    creatures = ", ".join(f'"{c}"' for c in spec.creature_pool)
    lines.append(f"    creatures = {{{creatures}}},")
    lines.append(f"    creatures_per_room = {{{spec.creatures_per_room[0]}, {spec.creatures_per_room[1]}}},")
    containers = ", ".join(f'"{c}"' for c in spec.loot_containers)
    lines.append(f"    containers = {{{containers}}},")
    lines.append(f"    loot_per_room = {{{spec.loot_per_room[0]}, {spec.loot_per_room[1]}}},")
    lines.append("  },")
    lines.append("}")
    lines.append(f"return {cfg_var}")
    return "\n".join(lines)
